name: CI

on:
  push:
    branches: [main, feature/branch]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo hello, world!

      - name: running a custom script
        run: |
          ls -al

      - name: Run a multi-line script
        run:
          echo Add other action to build,
          echo test, and deploy your project

      - name: check java version
        run: java --version

      - name: maven build
        run: mvn clean install

      - name: Docker version
        run: |
          docker -v
          docker images -a
      - name: docker build
        run: docker build . -t demo-java2.0
